[Icon Theme]
Name=Ikigai
Comment=Phosphor as a symbolic icon theme
Inherits=Cosmic,Pop,hicolor
Directories=scalable/actions,scalable/status,scalable/devices,scalable/places,scalable/categories,scalable/emblems,scalable/mimetypes,scalable/apps

[scalable/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/categories]
Context=Categories
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/emblems]
Context=Emblems
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=Mimetypes
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Apps
Size=16
MinSize=8
MaxSize=512
Type=Scalable
