[Icon Theme]
Name=Ikigai
Comment=Phosphor as a symbolic icon theme
Inherits=Cosmic,Pop,hicolor
Directories=16x16/actions,16x16/status,16x16/devices,16x16/places,16x16/categories,16x16/emblems,16x16/mimetypes,16x16/apps,scalable/actions,scalable/status,scalable/devices,scalable/places,scalable/categories,scalable/emblems,scalable/mimetypes,scalable/apps

[16x16/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/actions]
Context=Actions
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/status]
Context=Status
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/status]
Context=Status
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/devices]
Context=Devices
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/devices]
Context=Devices
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/places]
Context=Places
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/places]
Context=Places
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/categories]
Context=Categories
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/categories]
Context=Categories
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/emblems]
Context=Emblems
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/emblems]
Context=Emblems
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/mimetypes]
Context=Mimetypes
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/mimetypes]
Context=Mimetypes
Size=24
MinSize=21
MaxSize=512
Type=Scalable

[16x16/apps]
Context=Apps
Size=16
MinSize=8
MaxSize=20
Type=Scalable

[scalable/apps]
Context=Apps
Size=24
MinSize=21
MaxSize=512
Type=Scalable
