#!/usr/bin/env bash
# Generate shell/Icons.qml, the Phosphor icon name → glyph table, from Phosphor's own
# web font stylesheet (MIT). Code points are shared by every weight, so one table serves
# the regular and fill families. Pin matches the ttf-phosphor-icons package.
set -euo pipefail
REV=v2.1.2
DEST="$(cd "$(dirname "$0")/.." && pwd)/shell/Icons.qml"
CSS="$(mktemp)"
trap 'rm -f "$CSS"' EXIT
curl -fsSL -o "$CSS" "https://raw.githubusercontent.com/phosphor-icons/web/$REV/src/regular/style.css"
python3 - "$REV" "$DEST" "$CSS" <<'PY'
import re, sys
rev, dest, css = sys.argv[1], sys.argv[2], sys.argv[3]
glyphs = re.findall(r'\.ph\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', open(css).read())
if len(glyphs) < 1000:
    sys.exit(f"parsed only {len(glyphs)} glyphs; stylesheet format changed?")
rows = ",\n".join(f'        "{name}": "\\u{int(code, 16):04x}"' for name, code in glyphs)
open(dest, "w").write(f"""pragma Singleton
import Quickshell

// Generated by scripts/vendor-phosphor.sh from Phosphor {rev}; do not edit.
Singleton {{
    function glyph(name) {{
        return glyphs[name] || glyphs["question"];
    }}

    readonly property var glyphs: ({{
{rows}
    }})
}}
""")
print(f"vendored Icons.qml ({len(glyphs)} glyphs) @ {rev}")
PY
